### ISSUE TITLE
Feature request: Add tool Puppeteer to the work container

### ISSUE THREAD

**Issue by RensFeijen** [devilbox/docker-php-fpm#100]
Hey all,

I would like to propose that https://github.com/GoogleChrome/puppeteer be installed by default or using a flag in the `work` versions of this container. A lot of tools/packages/frameworks are starting to use this image testing, screenshots, PDF generation that is more reliable than `wkhtmltopdf` etc, for example: https://github.com/spatie/browsershot

Please let me know if you're interested. If you don't have the time to do it, I'm willing to create a PR for this.

Thanks in advance!

**Comment by cytopia** [comment]
@RensFeijen puppeteer is around ~282MB in size and will simply make the PHP image way too big.

You can however add this to your startup script, so it will automatically be installed during `docker-compose up`. See here for more details: https://devilbox.readthedocs.io/en/latest/autostart/custom-scripts-globally.html

I hope this is a satisfactory compromise.
