### ISSUE TITLE
How to realy send email to a true email box? 

### ISSUE THREAD

**Issue by ayang** [devilbox/docker-php-fpm#105]
regardless of ENABLE_MAIL is set, I can not send an email by php's mail function to my real email box. How can I do this?

**Comment by neradp** [comment]
You must use another smtp service, overwrite php.ini ...

**Comment by cytopia** [comment]
@ayang option will be addressed in current PR: https://github.com/devilbox/docker-php-fpm/pull/143

This allows you to start postfix without the catch-all in place via `ENABLE_MAIL=1`. You will still need to configure postfix yourself to your needs via the startup scripts (use `postconf` in a bash script to accomplish what you require)
