### ISSUE TITLE
<IfModule mod_php5.c> in .htaccess

### ISSUE THREAD

**Issue by maniconef** [devilbox/docker-php-fpm#114]
i have devilbox with apache2.4 and php5.6

in my .htaccess i have 
  php_value memory_limit 64M
    php_value memory_limit 256M
    php_value max_execution_time 18000
ecc......

Invalid command 'php_value', perhaps misspelled or defined by a module not included in the server configuration

the problem if apache not have mod_php
how i can resolve it

**Comment by cytopia** [comment]
You would do that via `php.ini` or `php-fpm.conf`:

* https://devilbox.readthedocs.io/en/latest/configuration-files/php-ini.html
* https://devilbox.readthedocs.io/en/latest/configuration-files/php-fpm-conf.html

**Comment by maniconef** [comment]
ok but i want use this
  php_admin_value auto_prepend_file "/var/www/xhgui/external/header.php"

where add this command
i had in virtualhost configuration but have same problem

Invalid command 'php_admin_value ', perhaps misspelled or defined by a module not included in the server configuration

**Comment by cytopia** [comment]
Try this: https://devilbox.readthedocs.io/en/latest/configuration-files/php-fpm-conf.html#id4

**Comment by cytopia** [comment]
@maniconef did that solve your issue?

**Comment by cytopia** [comment]
I am closing this due to missing reply for a long time. Feel free to give your feedback here to re-open.
