### ISSUE TITLE
Feature request: Allow users to override the command executed in the entrypoint

### ISSUE THREAD

**Issue by shaunchong** [devilbox/docker-php-fpm#121]
The current entrypoint script runs supervisor by default, but could it be possible to instead allow the user do issue their own startup command?

i.e.
at the end of `docker-entrypoint.sh`
`exec "$@"`

Then in the user's Dockerfile, one can run their own supervisor command with different arguments, or even run a php script:

`CMD ["php", "my-cron-script.php"]`

I can make these changes.

**Comment by cytopia** [comment]
@shaunchong I will look into this.

**Comment by cytopia** [comment]
@shaunchong it's merged
