### ISSUE TITLE
Update Sass

### ISSUE THREAD

**Issue by neradp** [devilbox/docker-php-fpm#123]
Hi,
can you update Ruby Sass tool to Dart Sass ?
Ruby Sass reached its EOL.

**Comment by cytopia** [comment]
@neradp can you point me to the documentation of how to install Dart Sass.

**Comment by neradp** [comment]
https://sass-lang.com/install

npm install -g sass

**Comment by neradp** [comment]
Hi your solution has some bug. You need remove rubby gem  scss_lint  too. If you wish to replace scss_lint with some never lint tooll for sass you can use: npm install stylelint stylelint-scss -g

I was upgrading devilbox container today and still getting Ruby Sass.

**Comment by cytopia** [comment]
@neradp correct, not yet upgraded in Devilbox. Will these days.
