### ISSUE TITLE
How to connect to MySQL in a docker container?

### ISSUE THREAD

**Issue by webcoderkz** [devilbox/docker-php-fpm#126]
I have MySQL in a docker container with exposed port `3306:3306`, so i can access it on the host machine using 127.0.0.1:3306 address, however devilbox php-fpm container cannot connect to it, says connection refuses. I have allowed mysql user to user any host `%`, but still, it cannot connect.

Launching container with the following command: `docker run -d --rm --name phpfpm5 -p 9001:9000 -v /srv/www:/srv/www devilbox/php-fpm:5.6-prod`

**Comment by science695** [comment]
127.0.0.1 is an address for localhost. It is relative to which computer / docker container you are running it from.

127.0.0.1 from your Host computer is not the same as 127.0.0.1 from the php container.

Try connecting using the name of the mysql docker container (i.e.: mysql:3306 if this is using devilbox's config)

**Comment by webcoderkz** [comment]
Thanks, i've figured out already. I had to use 172.17.0.1 (host machine) instead of 127.0.0.1
