### ISSUE TITLE
PHP 7.4 stable not yet available

### ISSUE THREAD

**Issue by llaville** [devilbox/docker-php-fpm#137]
Hello Cytopia,

I've tried to used PHP 7.4 php-pfm images from devilbox, but no stable PHP 7.4 version seems available.
Of course, i've tried current version 0.94 but also 0.95

After upgrading, i got this one : 
https://hub.docker.com/layers/devilbox/php-fpm/7.4-work-0.95/images/sha256-b1cc0ef307beeccac3413c3cf63c135ce5c6b523012f14f758b0b04dd0878303

But when I enter the container, here is the result 

```
devilbox@php-7.4.1-dev in /shared/httpd $ php -v
PHP 7.4.1-dev (cli) (built: Nov 30 2019 00:27:31) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.1-dev, Copyright (c), by Zend Technologies
    with Xdebug v2.8.0, Copyright (c) 2002-2019, by Derick Rethans
```

the devilbox php-fpm images were built 20 hours ago (when i write this issue), and official PHP docker images are avaiable since 2 days 
https://hub.docker.com/_/php/?tab=tags&page=1&name=7.4

What's wrong ?

**Comment by cytopia** [comment]
> but no stable PHP 7.4 version seems available.

Yes, it is still build from git sources out of the `PHP-7.4` branch: https://github.com/devilbox/docker-php-fpm-7.4/blob/master/Dockerfile#L84

It is actually the *stable*. You can see the differences to the official stable here: https://github.com/php/php-src/compare/PHP-7.4...php-7.4.0?expand=1

I will switch this nevertheless to the official PHP image to get rid of the `-dev` ;-)

**Comment by llaville** [comment]
@cytopia Thanks a lot for these informations !
