### ISSUE TITLE
PHP 7.2.28, 7.3.15 and 7.4.3 not available

### ISSUE THREAD

**Issue by llaville** [devilbox/docker-php-fpm#156]
Hello Cytopia,

Latest version of PHP are not available, probably due to an error in nightly deployment : see Github actions => https://github.com/devilbox/docker-php-fpm/actions/runs/54690173

It were officially published in Feb, 20 and available as Docker Images on Feb 26.

Almost one month now, that we should have new images of devilbox php-fpm available.

I know that your support is limited until end of this month, but could you have a look on it please !

Thanks
Laurent

**Comment by cytopia** [comment]
Working on it.

**Comment by llaville** [comment]
@cytopia i've tested new release 0.106 with php versions referenced by this issue, and all are ok for me !
