### ISSUE TITLE
Script quits without error

### ISSUE THREAD

**Issue by gacekssj4** [devilbox/docker-php-fpm#165]
I have strange issue.
It happens at kinda random times. Always around 2m20s. (+/-5s).
I rised 180s PHPFPM timeout. It does not happend other pure apache server. I spent quite time debugging it.

**Comment by cytopia** [comment]
@gacekssj4 could you provide some more details:

* how was it started
* what means the last sentence? it only happens with apache?

**Comment by cytopia** [comment]
Will close due to inactivity
