### ISSUE TITLE
Cannot set LC_ALL

### ISSUE THREAD

**Issue by finex** [devilbox/docker-php-fpm#166]
Hi, I'm trying to set LC_TIME but locale-gen is missing (I'm using devilbox/php-fpm:5.3-mods). What's the best practice to configure LC_ALL on this image? Thanks :-)

**Comment by cytopia** [comment]
@finex will be resolved here: https://github.com/devilbox/docker-php-fpm/pull/172

**Comment by finex** [comment]
Thank you :-)
