### ISSUE TITLE
PHP-Nightly failed each day since August 15

### ISSUE THREAD

**Issue by llaville** [devilbox/docker-php-fpm#169]
Hello @cytopia 
New images 5.5 to 7.4 are not available since 28 days now !

Hope you've noticed it, otherwise it's just a reminder

**Comment by cytopia** [comment]
Thanks for the heads-up. Seems it is failing due to drupalconsole.com/installer being down :-/

https://github.com/hechoendrupal/drupal-console/issues/4263

**Comment by llaville** [comment]
Thanks to quick reply. BTW, current 7.2-0.110 failed 
Reason is https://github.com/devilbox/docker-php-fpm/runs/1105495942?check_suite_focus=true#step:10:5841

**Comment by cytopia** [comment]
Already on it by the latest commit in that PR :-)

**Comment by llaville** [comment]
7.2 still fail (new reason)

**Comment by cytopia** [comment]
I might have to switch to GitHub Actions completely as the build time now exceeds what is available on Travis for free.
