### ISSUE TITLE
Docker Hub images 0.113 seems not updated

### ISSUE THREAD

**Issue by llaville** [devilbox/docker-php-fpm#176]
Hello @cytopia 

Docker Hub images corresponding to tag 0.113 was updated 15 days ago.
Github Action (PHP-Nightly) seems OK but no new images are available. 
Could you checks on your side please ?

Thanks in advance

**Comment by llaville** [comment]
Don't know if you did something, but images on docker hub was available 3 hours ago (when I write these lines).
So I'll close this report.

**Comment by cytopia** [comment]
@llaville yes, I did trigger it manually and also added it to Travis. Thanks for pointing this out.
