### ISSUE TITLE
Env Variable PHP

### ISSUE THREAD

**Issue by rodrigosandrin** [devilbox/docker-php-fpm#180]
Hi Guys, i need to pass the variable NLS_LANG inside de php, but the only way that i found to do this is editing the xml file in /usr/local/etc/php-fpm.conf. I add the line bellow inside<value name="environment">:

<value name="NLS_LANG">american_america.WE8ISO8859P1</value>

But this is the right way to do this? When i pass the variable with docker run -e, this dont pass inside the php (when i run the phpinfo();)

I have already change the directorys /etc/php-fpm-custom.d/charset.conf and /etc/php-custom.d/charset.ini but no effect.

I am using the image devilbox/php-fpm:5.2-prod

**Comment by cytopia** [comment]
This is the section to add them: https://github.com/cytopia/devilbox/blob/master/cfg/php-fpm-5.2/php-fpm.xml-example#L141
