### ISSUE TITLE
Use Official PHP 8.0 image

### ISSUE THREAD

**Issue by llaville** [devilbox/docker-php-fpm#187]
Hello Cytopia,

Now the PHP 8.0 stable version was released, could you use the official docker image rather than your own copy ?
Thanks 

https://github.com/devilbox/docker-php-fpm/blob/master/Dockerfiles/base/Dockerfile-8.0#L2

**Comment by cytopia** [comment]
@llaville currently not possible to switch to those as they haven't enabled `ffi` (which can only be enabled during php compile time with `--ffi` : https://www.php.net/manual/en/ffi.installation.php)

* See their build: https://github.com/docker-library/php/blob/master/8.0/buster/fpm/Dockerfile
* Compare to mine:  https://github.com/devilbox/docker-php-fpm-8.0/blob/master/Dockerfile#L185

I will make the switch as soon as they provide an `ffi` version.

**Comment by cytopia** [comment]
@llaville I've synced the Dockerfile witht the official one from PHP 8.0 with the exception of two things:

* enable `ffi`
* check out latest `8.0.x` git branch instead of fetching the tar.gz

So they're now pretty mich the same and I will switch to the official ones as soon as they enable `ffi`

https://github.com/devilbox/docker-php-fpm-8.0/pull/11

**Comment by llaville** [comment]
@cytopia While PHP 8.0.5 was released and now available, we still got a 8.0.3 version.

See latest nightly build https://github.com/devilbox/docker-php-fpm-8.0/runs/2484503053?check_suite_focus=true#step:4:753

**Comment by llaville** [comment]
@cytopia take care that building some extensions with `--with-openssl-dir` configuration now raise an error

```
Step 42/63 : RUN set -eux       && docker-php-ext-configure snmp --with-openssl-dir     && docker-php-ext-install -j$(getconf _NPROCESSORS_ONLN) snmp   && true
 ---> Running in 2a22071864cc
+ docker-php-ext-configure snmp --with-openssl-dir
Configuring for:
PHP Api Version:         20200930
Zend Module Api No:      20200930
Zend Extension Api No:   420200930
configure: error: unrecognized options: --with-openssl-dir
The command '/bin/sh -c set -eux        && docker-php-ext-configure snmp --with-openssl-dir     && docker-php-ext-install -j$(getconf _NPROCESSORS_ONLN) snmp       && true' returned a non-zero code: 1
Makefile:195: recipe for target 'build-mods' failed
make: *** [build-mods] Error 1
```

See https://github.com/php/php-src/commit/74380465ec8d868bd3d28d7cf73151642d195012 for change

And https://github.com/devilbox/docker-php-fpm/blob/master/build/ansible/group_vars/all/mods.yml#L925 for declaration

**Comment by llaville** [comment]
Another error with soap extension

```
Step 43/63 : RUN set -eux       && docker-php-ext-configure soap --with-libxml-dir=/usr         && docker-php-ext-install -j$(getconf _NPROCESSORS_ONLN) soap       && true
 ---> Running in 2384a379477d
+ docker-php-ext-configure soap --with-libxml-dir=/usr
Configuring for:
PHP Api Version:         20200930
Zend Module Api No:      20200930
Zend Extension Api No:   420200930
configure: error: unrecognized options: --with-libxml-dir
The command '/bin/sh -c set -eux        && docker-php-ext-configure soap --with-libxml-dir=/usr         && docker-php-ext-install -j$(getconf _NPROCESSORS_ONLN) soap       && true' returned a non-zero code: 1
Makefile:195: recipe for target 'build-mods' failed
make: *** [build-mods] Error 1
```

**Comment by llaville** [comment]
Another error with zip extension

```
Step 60/63 : RUN set -eux       && docker-php-ext-configure zip --with-zlib-dir=/usr --with-pcre-dir=/usr --with-libzip         && docker-php-ext-install -j$(getconf _NPROCESSORS_ONLN) zip        && true
 ---> Running in 8d5777d63746
+ docker-php-ext-configure zip --with-zlib-dir=/usr --with-pcre-dir=/usr --with-libzip
Configuring for:
PHP Api Version:         20200930
Zend Module Api No:      20200930
Zend Extension Api No:   420200930
configure: error: unrecognized options: --with-zlib-dir, --with-pcre-dir, --with-libzip
The command '/bin/sh -c set -eux        && docker-php-ext-configure zip --with-zlib-dir=/usr --with-pcre-dir=/usr --with-libzip         && docker-php-ext-install -j$(getconf _NPROCESSORS_ONLN) zip        && true' returned a non-zero code: 1
Makefile:195: recipe for target 'build-mods' failed
make: *** [build-mods] Error 1
```

See https://github.com/php/php-src/commit/c9830f1c2c936e766d3615ea7c4f37990e51a113#diff-0b8afd015a24799eb22ae162f979688e00ce2384472ae11994663cf2559aaa2d

And https://github.com/devilbox/docker-php-fpm/blob/master/build/ansible/group_vars/all/mods.yml#L1251 for declaration

**Comment by llaville** [comment]
@cytopia Following my previous comments, I've rebuilt PHP 8.0, 7.4 and 7.3 images with changes applied in commit https://github.com/llaville/docker-php-fpm/commit/7b12ecd2938917444cc7dd2040e6b5dae4cca49c, if you want to use it

**Comment by llaville** [comment]
@cytopia following my comment https://github.com/devilbox/docker-php-fpm/issues/187#issuecomment-830760566, I've used now official PHP 8.0 docker image without FFI support (my choice) in my fork (https://github.com/llaville/docker-php-fpm/commit/a2edbd96fc9a2a801e8254c382bc49156f321f0c)
Even if its seems a workaround seems possible : see my request at https://github.com/docker-library/php/issues/1112

**Comment by llaville** [comment]
@cytopia I've just tested new version of Devilbox 1.9.2 with docker-php-pfm image 8.0 but still have an issue with it ! 

See following output : 
```
devilbox@php-8.0.3 in /shared/httpd $ php -v
PHP 8.0.3 (cli) (built: Jun  5 2021 01:13:00) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.3, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.3, Copyright (c), by Zend Technologies
    with Xdebug v3.0.4, Copyright (c) 2002-2021, by Derick Rethans
devilbox@php-8.0.3 in /shared/httpd $ exit
logout
llaville@DESKTOP-83207V7:~/.devilbox$ git branch -v
* master f6bbdc72 Merge pull request #814 from cytopia/release/v1.9.2
llaville@DESKTOP-83207V7:~/.devilbox$ cat .env | grep 8.0
PHP_SERVER=8.0
#MYSQL_SERVER=mysql-8.0
#MYSQL_SERVER=percona-8.0
llaville@DESKTOP-83207V7:~/.devilbox$ cat docker-compose.override.yml | grep work-
    image: devilbox/php-fpm:${PHP_SERVER}-work-0.127
```
**Expected to have version 8.0.7**  but got version 8.0.3

While all seems good with latest PHP 7.4 release 
```
devilbox@php-7.4.20 in /shared/httpd $ php -v
PHP 7.4.20 (cli) (built: Jun  3 2021 21:55:37) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.20, Copyright (c), by Zend Technologies
    with Xdebug v3.0.4, Copyright (c) 2002-2021, by Derick Rethans
devilbox@php-7.4.20 in /shared/httpd $ exit
logout
llaville@DESKTOP-83207V7:~/.devilbox$ git branch -v
* master f6bbdc72 Merge pull request #814 from cytopia/release/v1.9.2
llaville@DESKTOP-83207V7:~/.devilbox$ cat .env | grep 7.4
PHP_SERVER=7.4
llaville@DESKTOP-83207V7:~/.devilbox$ cat docker-compose.override.yml | grep work-
    image: devilbox/php-fpm:${PHP_SERVER}-work-0.127
```

**Comment by cytopia** [comment]
I'm currently digging into this. Looks like it is somehow retrieving the wrong git tag: https://github.com/devilbox/docker-php-fpm-8.0/runs/2759736283?check_suite_focus=true#step:4:750

**Comment by cytopia** [comment]
Found it. PHP officially switched to GitHub after they had a breach. Created PR's

**Comment by cytopia** [comment]
Builds have been retriggered: https://github.com/devilbox/docker-php-fpm/actions/runs/913134620

**Comment by llaville** [comment]
I can't check it now, because I'm in travel, and I've a little internet connection.

**Comment by llaville** [comment]
@cytopia Back from travel and I've just tested new PHP 8.0 image: LGTM ! (php-fpm 0.127 tested)

**Comment by llaville** [comment]
I'll close this report because I used now my alternative project https://github.com/llaville/docker-php-toolbox that accept official PHP 8.0 docker image with FFI support.
