### ISSUE TITLE
Enabling PECL extension for PHP8 

### ISSUE THREAD

**Issue by taliptako** [devilbox/docker-php-fpm#189]
Can we enable xlswriter extension for php 8 build ?

**Comment by cytopia** [comment]
Should be available shortly

**Comment by taliptako** [comment]
thank you seems like PECL added to the official PHP docker image again.

**Comment by cytopia** [comment]
> thank you seems like PECL added to the official PHP docker image again.

Yes, also saw this and did it now for PHP 8.0 and PHP 8.1. This makes it easier to add more extensions. See list of all new extensions added here: https://github.com/devilbox/docker-php-fpm/pull/190
