### ISSUE TITLE
Cannot retrieve the value of the cfg_file_path configuration setting

### ISSUE THREAD

**Issue by llaville** [devilbox/docker-php-fpm#192]
Hello Cytopia,

When we want to know where *.ini files loaded from, we have many solutions.

* In CLI version, the more easy is to execute following command: 
```php --ini```
And look line begining with `Configuration File (php.ini) Path:`

* In php script, we have to use the PHP's [get_cfg_var](https://www.php.net/manual/en/function.get-cfg-var) function with the `cfg_file_path` argument.

On my Windows 10 Laptop with WSL2 and Ubuntu 16.04 distribution, I got 

```
llaville@LAPTOP-7JMHIOJJ:~/.devilbox$ php -r "echo get_cfg_var('cfg_file_path'), PHP_EOL;"
/etc/php/7.2/cli/php.ini
llaville@LAPTOP-7JMHIOJJ:~/.devilbox$ php --ini
Configuration File (php.ini) Path: /etc/php/7.2/cli
Loaded Configuration File:         /etc/php/7.2/cli/php.ini
Scan for additional .ini files in: /etc/php/7.2/cli/conf.d
Additional .ini files parsed:      /etc/php/7.2/cli/conf.d/10-opcache.ini,
/etc/php/7.2/cli/conf.d/10-pdo.ini,
/etc/php/7.2/cli/conf.d/20-calendar.ini,
/etc/php/7.2/cli/conf.d/20-ctype.ini,
/etc/php/7.2/cli/conf.d/20-exif.ini,
/etc/php/7.2/cli/conf.d/20-fileinfo.ini,
/etc/php/7.2/cli/conf.d/20-ftp.ini,
/etc/php/7.2/cli/conf.d/20-gettext.ini,
/etc/php/7.2/cli/conf.d/20-iconv.ini,
/etc/php/7.2/cli/conf.d/20-json.ini,
/etc/php/7.2/cli/conf.d/20-phar.ini,
/etc/php/7.2/cli/conf.d/20-posix.ini,
/etc/php/7.2/cli/conf.d/20-readline.ini,
/etc/php/7.2/cli/conf.d/20-shmop.ini,
/etc/php/7.2/cli/conf.d/20-sockets.ini,
/etc/php/7.2/cli/conf.d/20-sysvmsg.ini,
/etc/php/7.2/cli/conf.d/20-sysvsem.ini,
/etc/php/7.2/cli/conf.d/20-sysvshm.ini,
/etc/php/7.2/cli/conf.d/20-tokenizer.ini

llaville@LAPTOP-7JMHIOJJ:~/.devilbox$ php -v
PHP 7.2.24-0ubuntu0.18.04.3 (cli) (built: Feb 11 2020 15:55:52) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.24-0ubuntu0.18.04.3, Copyright (c) 1999-2018, by Zend Technologies
```

**Issue are in Docker Containers** (latest release 0.123 used)

```
devilbox@php-7.4.13 in /shared/httpd $ php -v
PHP 7.4.13 (cli) (built: Dec 11 2020 08:31:11) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.13, Copyright (c), by Zend Technologies
    with Xdebug v3.0.1, Copyright (c) 2002-2020, by Derick Rethans
devilbox@php-7.4.13 in /shared/httpd $ php -r "echo get_cfg_var('cfg_file_path'), PHP_EOL;"

devilbox@php-7.4.13 in /shared/httpd $ php --ini
Configuration File (php.ini) Path: /usr/local/etc/php
Loaded Configuration File:         (none)
Scan for additional .ini files in: /usr/local/etc/php/conf.d
Additional .ini files parsed:      /usr/local/etc/php/conf.d/devilbox-runtime-sendmail.ini,
/usr/local/etc/php/conf.d/devilbox-runtime-timezone.ini,
/usr/local/etc/php/conf.d/docker-php-ext-amqp.ini,
/usr/local/etc/php/conf.d/docker-php-ext-apcu.ini,
/usr/local/etc/php/conf.d/docker-php-ext-bcmath.ini,
/usr/local/etc/php/conf.d/docker-php-ext-bz2.ini,
/usr/local/etc/php/conf.d/docker-php-ext-calendar.ini,
/usr/local/etc/php/conf.d/docker-php-ext-dba.ini,
/usr/local/etc/php/conf.d/docker-php-ext-enchant.ini,
/usr/local/etc/php/conf.d/docker-php-ext-exif.ini,
/usr/local/etc/php/conf.d/docker-php-ext-ffi.ini,
/usr/local/etc/php/conf.d/docker-php-ext-gd.ini,
/usr/local/etc/php/conf.d/docker-php-ext-gettext.ini,
/usr/local/etc/php/conf.d/docker-php-ext-gmp.ini,
/usr/local/etc/php/conf.d/docker-php-ext-igbinary.ini,
/usr/local/etc/php/conf.d/docker-php-ext-imagick.ini,
/usr/local/etc/php/conf.d/docker-php-ext-imap.ini,
/usr/local/etc/php/conf.d/docker-php-ext-intl.ini,
/usr/local/etc/php/conf.d/docker-php-ext-ldap.ini,
/usr/local/etc/php/conf.d/docker-php-ext-mcrypt.ini,
/usr/local/etc/php/conf.d/docker-php-ext-memcache.ini,
/usr/local/etc/php/conf.d/docker-php-ext-memcached.ini,
/usr/local/etc/php/conf.d/docker-php-ext-mongodb.ini,
/usr/local/etc/php/conf.d/docker-php-ext-msgpack.ini,
/usr/local/etc/php/conf.d/docker-php-ext-mysqli.ini,
/usr/local/etc/php/conf.d/docker-php-ext-oauth.ini,
/usr/local/etc/php/conf.d/docker-php-ext-opcache.ini,
/usr/local/etc/php/conf.d/docker-php-ext-pcntl.ini,
/usr/local/etc/php/conf.d/docker-php-ext-pdo_dblib.ini,
/usr/local/etc/php/conf.d/docker-php-ext-pdo_firebird.ini,
/usr/local/etc/php/conf.d/docker-php-ext-pdo_mysql.ini,
/usr/local/etc/php/conf.d/docker-php-ext-pdo_oci.ini,
/usr/local/etc/php/conf.d/docker-php-ext-pdo_pgsql.ini,
/usr/local/etc/php/conf.d/docker-php-ext-pgsql.ini,
/usr/local/etc/php/conf.d/docker-php-ext-phalcon.ini,
/usr/local/etc/php/conf.d/docker-php-ext-pspell.ini,
/usr/local/etc/php/conf.d/docker-php-ext-psr.ini,
/usr/local/etc/php/conf.d/docker-php-ext-redis.ini,
/usr/local/etc/php/conf.d/docker-php-ext-shmop.ini,
/usr/local/etc/php/conf.d/docker-php-ext-snmp.ini,
/usr/local/etc/php/conf.d/docker-php-ext-soap.ini,
/usr/local/etc/php/conf.d/docker-php-ext-sockets.ini,
/usr/local/etc/php/conf.d/docker-php-ext-sodium.ini,
/usr/local/etc/php/conf.d/docker-php-ext-solr.ini,
/usr/local/etc/php/conf.d/docker-php-ext-ssh2.ini,
/usr/local/etc/php/conf.d/docker-php-ext-sysvmsg.ini,
/usr/local/etc/php/conf.d/docker-php-ext-sysvsem.ini,
/usr/local/etc/php/conf.d/docker-php-ext-sysvshm.ini,
/usr/local/etc/php/conf.d/docker-php-ext-tidy.ini,
/usr/local/etc/php/conf.d/docker-php-ext-uploadprogress.ini,
/usr/local/etc/php/conf.d/docker-php-ext-vips.ini,
/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini,
/usr/local/etc/php/conf.d/docker-php-ext-xlswriter.ini,
/usr/local/etc/php/conf.d/docker-php-ext-xmlrpc.ini,
/usr/local/etc/php/conf.d/docker-php-ext-xsl.ini,
/usr/local/etc/php/conf.d/docker-php-ext-yaml.ini,
/usr/local/etc/php/conf.d/docker-php-ext-zip.ini,
/usr/local/etc/php/conf.d/xxx-devilbox-default-php.ini,
/usr/local/etc/php/conf.d/yyy-devilbox-user-runtime-php.ini,
/usr/local/etc/php/conf.d/yyy-devilbox-user-runtime-xdebug.ini,
/usr/local/etc/php/conf.d/zzz-entrypoint-logfiles.ini
```

I got **Loaded Configuration File:         (none)** while I've a custom php.ini file

```
llaville@LAPTOP-7JMHIOJJ:~/.devilbox$ ll cfg/php-ini-7.4/
total 28
drwxr-xr-x  2 llaville llaville 4096 Dec 20 17:24 ./
drwxr-xr-x 61 llaville llaville 4096 Nov 14 19:23 ../
-rw-r--r--  1 llaville llaville    0 Nov 14 19:23 .keepme
-rw-r--r--  1 llaville llaville  834 Nov 14 19:23 README.md
-rw-r--r--  1 llaville llaville 1544 Nov 14 19:23 devilbox-php.ini-default
-rw-r--r--  1 llaville llaville 1057 Dec 14 07:19 devilbox-php.ini-xdebug
-rw-r--r--  1 llaville llaville 1406 Dec 20 17:24 php.ini
-rw-r--r--  1 llaville llaville  988 Dec 18 07:48 xdebug.ini
```

Confirmed by the intranetDevilbox PHP info panel 

![localhost_config_php_php](https://user-images.githubusercontent.com/364342/102722283-752ee280-4300-11eb-9ea7-0ff2928b522a.png)

I'm expected to have the same behavior with `get_cfg_var('cfg_file_path')` with PHP native version (outside container) and PHP containerized version !

Tested at least with images 7.4 and 8.0 giving the same false results.

**Comment by llaville** [comment]
Here is an example online on one of my project that use this php function 
https://github.com/llaville/php-compatinfo-db/runs/1655213992?check_suite_focus=true#step:7:10

And the code is there :  https://github.com/llaville/php-compatinfo-db/blob/master/src/Infrastructure/ProjectRequirements.php#L107

And when I run this code on php container (whatever version 7.x or 8.0), i got : 

```
PHP CompatInfoDB Requirements Checker
=====================================

 > Using PHP 8.0.0
 > PHP is using the following php.ini file:
   WARNING: No configuration file (php.ini) used by PHP!

> Checking PHP CompatInfoDB requirements:
   [x] PHP version must be at least 7.2.0
   [x] pdo_sqlite extension must be available
   [x] Check if source "/home/devilbox/.cache/bartlett/compatinfo-db.sqlite" can be reached
   [x] Check if tables exists in database
   [x] Check if platforms are available in database



 [OK] Your system is ready to run the application.

```
Noticed the `WARNING: No configuration file (php.ini) used by PHP!`

**Comment by cytopia** [comment]
@llaville your custom loaded php ini files are prefixed to guarantee order and therefore ensure they're not overwritten by base ini files.

> **Issue are in Docker Containers** (latest release 0.123 used)
> 
> ```
> devilbox@php-7.4.13 in /shared/httpd $ php --ini
> Configuration File (php.ini) Path: /usr/local/etc/php
> Loaded Configuration File:         (none)
> Scan for additional .ini files in: /usr/local/etc/php/conf.d
> Additional .ini files parsed:      /usr/local/etc/php/conf.d/devilbox-runtime-sendmail.ini,
> ...
> /usr/local/etc/php/conf.d/yyy-devilbox-user-runtime-php.ini,
> /usr/local/etc/php/conf.d/yyy-devilbox-user-runtime-xdebug.ini,
> /usr/local/etc/php/conf.d/zzz-entrypoint-logfiles.ini
> ```

So they start with `yyy-devilbox-user-runtime-` And there you have both of your custom ones:

```
/usr/local/etc/php/conf.d/yyy-devilbox-user-runtime-php.ini,
/usr/local/etc/php/conf.d/yyy-devilbox-user-runtime-xdebug.ini,
```

**Comment by cytopia** [comment]
Just to clear things up:

* Everyhing starting with `docker-php-ext-*` is a default from the PHP images (it just contains enabled extensions) These are also the files that are being removed during startup if you disable a PHP extension via `.env`
* The `xxx-devilbox-default-php.ini` provides default values as defined here: https://github.com/devilbox/docker-php-fpm/blob/master/build/ansible/group_vars/all/all-php-settings.yml
* The `yyy-devilbox-user-runtime-*` is your custom configuration from the `php-ini-*/` directories within the Devilbox GitHub directory
* And finally the `zzz-entrypoint-*` contains any customization set via `.env` file

**Comment by evgeny-2019** [comment]
@cytopia, I cannot configure xdebug due to PHPStorm does not see php.ini. I attach a screenshot. What can I do to make PHPStorm see php.ini? 
![image](https://user-images.githubusercontent.com/66534498/122698986-2a5f3a80-d251-11eb-9955-83170e874efa.png)

> Additional .ini files parsed: /usr/local/etc/php/conf.d/devilbox-runtime-sendmail.ini, /usr/local/etc/php/conf.d/devilbox-runtime-timezone.ini, /usr/local/etc/php/conf.d/docker-php-ext-amqp.ini, /usr/local/etc/php/conf.d/docker-php-ext-apcu.ini, /usr/local/etc/php/conf.d/docker-php-ext-bcmath.ini, /usr/local/etc/php/conf.d/docker-php-ext-bz2.ini, /usr/local/etc/php/conf.d/docker-php-ext-calendar.ini, /usr/local/etc/php/conf.d/docker-php-ext-dba.ini, /usr/local/etc/php/conf.d/docker-php-ext-enchant.ini, /usr/local/etc/php/conf.d/docker-php-ext-exif.ini, /usr/local/etc/php/conf.d/docker-php-ext-gd.ini, /usr/local/etc/php/conf.d/docker-php-ext-gettext.ini, /usr/local/etc/php/conf.d/docker-php-ext-gmp.ini, /usr/local/etc/php/conf.d/docker-php-ext-igbinary.ini, /usr/local/etc/php/conf.d/docker-php-ext-imagick.ini, /usr/local/etc/php/conf.d/docker-php-ext-imap.ini, /usr/local/etc/php/conf.d/docker-php-ext-interbase.ini, /usr/local/etc/php/conf.d/docker-php-ext-intl.ini, /usr/local/etc/php/conf.d/docker-php-ext-ldap.ini, /usr/local/etc/php/conf.d/docker-php-ext-mcrypt.ini, /usr/local/etc/php/conf.d/docker-php-ext-memcache.ini, /usr/local/etc/php/conf.d/docker-php-ext-memcached.ini, /usr/local/etc/php/conf.d/docker-php-ext-mongodb.ini, /usr/local/etc/php/conf.d/docker-php-ext-msgpack.ini, /usr/local/etc/php/conf.d/docker-php-ext-mysqli.ini, /usr/local/etc/php/conf.d/docker-php-ext-oauth.ini, /usr/local/etc/php/conf.d/docker-php-ext-opcache.ini, /usr/local/etc/php/conf.d/docker-php-ext-pcntl.ini, /usr/local/etc/php/conf.d/docker-php-ext-pdo_dblib.ini, /usr/local/etc/php/conf.d/docker-php-ext-pdo_firebird.ini, /usr/local/etc/php/conf.d/docker-php-ext-pdo_mysql.ini, /usr/local/etc/php/conf.d/docker-php-ext-pdo_oci.ini, /usr/local/etc/php/conf.d/docker-php-ext-pdo_pgsql.ini, /usr/local/etc/php/conf.d/docker-php-ext-pgsql.ini, /usr/local/etc/php/conf.d/docker-php-ext-pspell.ini, /usr/local/etc/php/conf.d/docker-php-ext-recode.ini, /usr/local/etc/php/conf.d/docker-php-ext-redis.ini, /usr/local/etc/php/conf.d/docker-php-ext-shmop.ini, /usr/local/etc/php/conf.d/docker-php-ext-snmp.ini, /usr/local/etc/php/conf.d/docker-php-ext-soap.ini, /usr/local/etc/php/conf.d/docker-php-ext-sockets.ini, /usr/local/etc/php/conf.d/docker-php-ext-sodium.ini, /usr/local/etc/php/conf.d/docker-php-ext-solr.ini, /usr/local/etc/php/conf.d/docker-php-ext-ssh2.ini, /usr/local/etc/php/conf.d/docker-php-ext-sysvmsg.ini, /usr/local/etc/php/conf.d/docker-php-ext-sysvsem.ini, /usr/local/etc/php/conf.d/docker-php-ext-sysvshm.ini, /usr/local/etc/php/conf.d/docker-php-ext-tidy.ini, /usr/local/etc/php/conf.d/docker-php-ext-uploadprogress.ini, /usr/local/etc/php/conf.d/docker-php-ext-vips.ini, **/usr/local/etc/php/conf.d/docker-php-ext-wddx.ini, /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini**, /usr/local/etc/php/conf.d/docker-php-ext-xlswriter.ini, /usr/local/etc/php/conf.d/docker-php-ext-xmlrpc.ini, /usr/local/etc/php/conf.d/docker-php-ext-xsl.ini, /usr/local/etc/php/conf.d/docker-php-ext-yaml.ini, **/usr/local/etc/php/conf.d/docker-php-ext-zip.ini, /usr/local/etc/php/conf.d/xxx-devilbox-default-php.ini**, /usr/local/etc/php/conf.d/yyy-devilbox-user-runtime-php.ini, /usr/local/etc/php/conf.d/zzz-entrypoint-logfiles.ini

**Comment by llaville** [comment]
Explains are enough and LGTM !
