### ISSUE TITLE
devilbox/php-fpm:8.1-work not using latest version PHP8.1.2 ??

### ISSUE THREAD

**Issue by dgoosens** [devilbox/docker-php-fpm#227]
hi

I must be doing something stupid... or missing some info...

I'm using the `devilbox/php-fpm:8.1-work` container but the PHP version that comes with it appears to be `PHP 8.1.0-dev (cli) (built: Aug  7 2021 00:21:29) (NTS)`  

Yet, when pulling `devilbox/php-fpm-8.1` which, if I'm not mistaken, is the base image for `devilbox/php-fpm:8.1-work`, I'm getting `PHP 8.1.2 (cli) (built: Feb 14 2022 00:36:16) (NTS)` which is the version I want and would expect in `devilbox/php-fpm:8.1-work`

Could someone indicate what I'm missing ?

Thanks a lot  
dGo

**Comment by cytopia** [comment]
Do a `docker pull devilbox/php-fpm:8.1-work` this should give you the latest.

**Comment by dgoosens** [comment]
hi @cytopia 

thanks...  
nope, that did not change anything...

BUT... when adding the release tag, it does work  
ie `devilbox/php-fpm:8.1-work-0.133` 

Could it be, for some reason `:latest` points to the wrong release ?

**Comment by dgoosens** [comment]
strange indeed

this does work as expected:

```bash
docker run devilbox/php-fpm:8.1-work php -v
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
PHP 8.1.2 (cli) (built: Feb 14 2022 00:36:16) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.2, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.2, Copyright (c), by Zend Technologies
    with Xdebug v3.1.3, Copyright (c) 2002-2022, by Derick Rethans
```

**Comment by cytopia** [comment]
> 

Confirmed on my side. Pulled as stated above and have the latest 8.1.2 version build today.

**Comment by dgoosens** [comment]
right....  
blows me, but just redid the exact same manipulation    
and now it appears to be working as expected

sorry, looks like I alerted you for nothing
