### ISSUE TITLE
PHP modules don't exist

### ISSUE THREAD

**Issue by valentinocossar** [devilbox/docker-php-fpm#229]
Hi, I'm using the `devilbox/php-fpm:8.0-prod` image inside a Dockerfile built by a `docker-compose.yml` file, I'm providing the `ENABLE_MODULES` env var with the full list of PHP modules supported by `php-fpm:8.0-prod` but I get these warnings:

![image](https://user-images.githubusercontent.com/4087384/154262584-065340f3-970d-4d15-87bf-069dac87d3b1.png)

What am I doing wrong?

Thank you for the support!

**Comment by cytopia** [comment]
The `ENABLE_MODULES` variable will create a config for each item and enable it. If it is already enabled (as is in your case), PHP tries to load it twice and yields this warning. So no need to enable them, as they're enabled already by default.

You can see a more detailed list about what is enabled by default and what not here: https://github.com/cytopia/devilbox#available-php-modules

**Comment by cytopia** [comment]
Depends on what is in your `ENABLE_MODULES`. But in general, these warnings are never fake

**Comment by valentinocossar** [comment]
Ok, I'm telling that are fake because modules exist and are already enabled, now I've understood that enabling modules that are already enabled is not a best practice, in fact I've removed `ENABLE_MODULES` because I don't need it.
