### ISSUE TITLE
Need Help/Requested Feature: chromium-chromedriver firefox-geckodriver

### ISSUE THREAD

**Issue by diaboloshogunate** [devilbox/docker-php-fpm#240]
I am trying to run end to end test with [pather](https://github.com/symfony/panther) which requires the `chromium-chromedriver firefox-geckodriver` packages to be installed.

Can we have these installed by default?
If not how can I get them installed?

**Comment by cytopia** [comment]
@diaboloshogunate I try to keep the images here rather small, as they update frequently.

However, I've been working on a community version for the PHP-FPM images where such thing will be easily possible.
I haven't made it an official announcement yet,  but the repository went public yesterday. Have a look. You can either take over a new project, which has pather installed, or just build it locally:

https://github.com/devilbox/docker-php-fpm-community/

I am going to close this feature request here and you can take a look at the repo link listed abve.
