### ISSUE TITLE
Permission error when creating directories using php-fpm:7.2-prod

### ISSUE THREAD

**Issue by realnsleo** [devilbox/docker-php-fpm#58]
Hi,
This is more of a request and I hope someone can help me. I will be entirely grateful. I am building an application on PHP with SLIM framework using Twig as a view engine. My application is powered by nginx. I am building a container for production and I am using devilbox (awesome btw) with php-fpm:7.2-prod. Everything works well except for this error:

```
2018/11/01 19:10:37 [error] 31#31: *1 FastCGI sent in stderr: "PHP message: Slim Application Error:
rbWeb    | Type: RuntimeException
rbWeb    | Message: Unable to create the cache directory (/var/www/config/../cache/0c).
rbWeb    | File: /var/www/vendor/twig/twig/lib/Twig/Cache/Filesystem.php
```
I have spent close to 26 hours trying to figure out what is wrong with no luck. I am quite new to docker and I hope someone out there can point me into the right direction. This is my Dockerfile

```
FROM devilbox/php-fpm:7.2-prod

# Copy composer scripts
COPY ./composer.lock ./composer.json /var/www/

# Set the working directory
WORKDIR /var/www

# Install Git as it's needed for composer
# install git
RUN apt-get update \
    && apt-get install --assume-yes git zip unzip

# Install Composer
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
    && php composer-setup.php \
    && php -r "unlink('composer-setup.php');" \
    && php composer.phar install --no-dev --no-scripts \
    && rm composer.phar

# Create Cache directory for SLIM
RUN mkdir /var/www/cache

# Copy all files from my development to the container (with .dockerignore enforced)
COPY . /var/www

# Fix permissions for my folders
RUN chown -R www-data:www-data /var/www
RUN chown -R www-data:www-data /var/www/cache
RUN chown -R www-data:www-data /var/www/logs
```
I would really appreciate if anyone would suggest a fix. Thank you so much.

**Comment by realnsleo** [comment]
Oh man. I don't know how to thank you enough. I managed to fix it using your guidance. Thanks so much. And do keep up the awesome work. May the force be with you kind sir.

**Comment by cytopia** [comment]
You're welcome. Sometimes its the little things that keep us busy for many hours. :-)
