### ISSUE TITLE
PHP 7.3 causing nginx response errors

### ISSUE THREAD

**Issue by DenzoNL** [devilbox/docker-php-fpm#75]
When using the PHP 7.3 version of this image (either the work or mods variant, haven't tested the others), I'm getting `502 Bad Gateway` errors for 80% of the requests. There's nothing in the `php-fpm` error log, but the nginx error log produces the following error for each request:

```log
[error] 102#102: *1 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 192.168.128.1, server: enigma.localhost, request: "GET /nova/ HTTP/1.1", upstream: "fastcgi://192.168.128.4:9000", host: "enigma.localhost"
```

However, not all requests fail. I haven't been able to pinpoint the issue of what's causing it, but I do know that the issue is not present with the PHP 7.2 version of this image.

If it matters anything, I am not using the full devilbox suite, but have built my own `docker-compose.yml` file with the devilbox images for `nginx` and `php-fpm` along with the official images for `redis` and `mariadb`

**Comment by cytopia** [comment]
@DenzoNL this error might be related to its Xdebug module. Could you disable Xdebug for PHP 7.3 and see if that solves the issue. I had similar errors with it segfaulting on phpMyAdmin if Xdebug was enabled.

**Comment by DenzoNL** [comment]
> @DenzoNL this error might be related to its Xdebug module. Could you disable Xdebug for PHP 7.3 and see if that solves the issue. I had similar errors with it segfaulting on phpMyAdmin if Xdebug was enabled.

Adding `- DISABLE_MODULES=xdebug` has indeed solved the issue, thank you very much!

**Comment by cytopia** [comment]
Great to hear. The `xdebug` module is still beta as can be seen here: https://pecl.php.net/package/xdebug
I keep you updated once I have the stable version on PHP 7.3

**Comment by DenzoNL** [comment]
Thanks @cytopia!
